### ISSUE TITLE
Starting rotation only works for first two tabs in newest version

### ISSUE THREAD

**Issue by preexo** [KevinSheedy/chrome-tab-rotate#35]
Suddenly, when starting the rotation, only the first two tabs work. All other tabs go to this URL:
chrome-extension://pjgjpabbgnnoohijnillgbckikfkbjed/

And the browser displays: Your file was not found It may have been moved or deleted. ERR_FILE_NOT_FOUND

![screenshot 2019-02-11 at 6 50 36 pm](https://user-images.githubusercontent.com/1478410/52558649-004e1000-2e2e-11e9-8eb3-c5d7cf658ae3.png)

**Comment by KevinSheedy** [comment]
Hi @preexo
Could you attach your config please

**Comment by Jacques-Musoni** [comment]
Hi @KevinSheedy ,

I have the same Problem. I think this happens if you set the tabReloadIntervalSeconds to 0. 
Here is an Example:

``{
  "settingsReloadIntervalMinutes": 1,
  "fullscreen": false,
  "autoStart": false,
  "websites": [
    {
      "url": "https://www.patreon.com/kevdev",
      "duration": 10,
      "tabReloadIntervalSeconds": 0
    },
    {
      "url": "chrome-extension://pjgjpabbgnnoohijnillgbckikfkbjed/src/settings.html",
      "duration": 10,
      "tabReloadIntervalSeconds": 0
    },
    {
      "url": "https://github.com/KevinSheedy/chrome-tab-rotate.git",
      "duration": 10,
      "tabReloadIntervalSeconds": 0
    },
    {
      "url": "https://chrome.google.com/webstore/detail/tab-rotate/pjgjpabbgnnoohijnillgbckikfkbjed",
      "duration": 10,
      "tabReloadIntervalSeconds": 0
    },
    {
      "url": "https://ie.linkedin.com/in/kevinsheedy",
      "duration": 10,
      "tabReloadIntervalSeconds": 0
    }
  ]
}

**Comment by KevinSheedy** [comment]
Thanks @Jacques-Musoni 
I've reproduced the issue based on your config and pushed out a hotfix to address the issue: 0.3.1
The Chrome Store can take up to 60 minutes before making the update available.
Once it goes live, could you verify that it's working please?

**Comment by Jacques-Musoni** [comment]
Hi @KevinSheedy 
Its working again. 
Thank you very much!

**Comment by preexo** [comment]
Still not working for me though @KevinSheedy It not shows a blank one without an error though, so something has changed :)
![screenshot 2019-02-12 at 10 12 48 am](https://user-images.githubusercontent.com/1478410/52606854-03d5ab80-2eaf-11e9-8c89-8016eb7f0f93.png)
![screenshot 2019-02-12 at 10 13 24 am](https://user-images.githubusercontent.com/1478410/52606859-09cb8c80-2eaf-11e9-8626-59b6bf722cd8.png)

My version is 0.3.4 

The json is

```
{
  "enableAutoReload": true,
  "settingsReloadIntervalMinutes": 1,
  "fullscreen": true,
  "autoStart": false,
  "websites" : [
    {
      "url" : "https://www.google.com/",
      "duration" : 40,
      "tabReloadIntervalSeconds": 10
    },
    {
      "url" : "https://www.google.com/",
      "duration" : 20,
      "tabReloadIntervalSeconds": 1000
    },
    {
      "url" : "https://www.google.com/",
      "duration" : 20,
      "tabReloadIntervalSeconds": 1000
    }
   
     
  ]
}
```

Please see screenshots attached

**Comment by KevinSheedy** [comment]
Hi @preexo 
In order to better support low-power devices like RasberryPi / PC-sticks, I've changed the default algorithm to "lazy load" the websites. So rather than load all the websites simultaneously on startup, it now loads the first two on startup, then preloads each additional site "just in time" ie just before it is due to be displayed.

I've tested the config you sent on and it seems to be functioning ok, but with the new algorithm ie the 3rd site is loaded later, but it's still loaded before it gets displayed.

**Comment by VivaLaRobo** [comment]
@KevinSheedy we are using Pis in our office and they are not loading the 3rd, 4th, or 5th tabs even after 60 seconds. Version 0.3.4

**Comment by KevinSheedy** [comment]
Hi @VivaLaRobo, could you add your config file please

**Comment by VivaLaRobo** [comment]
@KevinSheedy it's the default one that is loaded from the extension:

`{
  "settingsReloadIntervalMinutes": 1,
  "fullscreen": false,
  "autoStart": false,
  "websites": [
    {
      "url": "https://www.patreon.com/kevdev",
      "duration": 10,
      "tabReloadIntervalSeconds": 15
    },
    {
      "url": "chrome-extension://pjgjpabbgnnoohijnillgbckikfkbjed/src/settings.html",
      "duration": 10,
      "tabReloadIntervalSeconds": 15
    },
    {
      "url": "https://github.com/KevinSheedy/chrome-tab-rotate.git",
      "duration": 10,
      "tabReloadIntervalSeconds": 300
    },
    {
      "url": "https://chrome.google.com/webstore/detail/tab-rotate/pjgjpabbgnnoohijnillgbckikfkbjed",
      "duration": 10,
      "tabReloadIntervalSeconds": 15
    },
    {
      "url": "https://ie.linkedin.com/in/kevinsheedy",
      "duration": 10,
      "tabReloadIntervalSeconds": 15
    }
  ]
}`

**Comment by KevinSheedy** [comment]
Ok, I just reproduced a bug whereby it wouldn't load the tabs after loading the config file from a remote location.

Could you confirm, were you loading the config form a url or entering it directly in the text box?

I've pushed out a fix for the remote config issue:
0.3.5

**Comment by VivaLaRobo** [comment]
@KevinSheedy we're loading our configs from a URL

**Comment by VivaLaRobo** [comment]
@KevinSheedy I can confirm the latest update is working on my MacBook Pro using a URL

However it is still not working properly on the Pi

**Comment by KevinSheedy** [comment]
@VivaLaRobo thanks for testing that out.
Are you seeing different behaviour on the Pi vs the Macbook?
Could you provide details of the differences? Has the Pi definitely updated?
Thanks

**Comment by VivaLaRobo** [comment]
@KevinSheedy slightly odd behavior. the macbook is working as expected. It loads the first 2 tabs then  slowly loads the other 3. 

on the Pi it loads the first 2 tabs, then slowly loads the 4th tab ? but not the 3rd or 5th tab.

**Comment by preexo** [comment]
It works fine for us now, indeed it loads the other tabs just before it rotates to them. @KevinSheedy 
Is there an option to disable that feature though? We regularly pause and manually change tabs. E.g. We are doing our standups on the screen that is rotating, by pausing and changing to the tab with the scrum board :D

**Comment by KevinSheedy** [comment]
Good point @preexo. I've raised this as a new issue here:
https://github.com/KevinSheedy/chrome-tab-rotate/issues/39

**Comment by KevinSheedy** [comment]
New config flag available in v 0.4.0

`"lazyLoadTabs": false`

@preexo could you test this please?
Thanks

**Comment by VivaLaRobo** [comment]
Hello @KevinSheedy I can confirm the 0.4.0 release has fixed the previous issues with the Pi. Thank you for fixing!!
